version: "3.9"

services:
  # ─────────── Vue + Nginx ───────────
  frontend:
    image: ghcr.io/now-eat-krap/one-more-coin/frontend:latest
    ports:
      - "80:80"
    depends_on: [spring, fastapi]

  # ─────────── Spring Boot ───────────
  spring:
    image: ghcr.io/now-eat-krap/one-more-coin/backend-java:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}

      NAVER_CLIENT_ID:     ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      GOOGLE_CLIENT_ID:    ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID:     ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      OAUTH_REDIRECT_BASE: ${OAUTH_REDIRECT_BASE}

      JWT_SECRET: ${JWT_SECRET}
    depends_on: [redis]

  # ─────────── FastAPI ───────────
  fastapi:
    image: ghcr.io/now-eat-krap/one-more-coin/backend-python:latest
    ports:
      - "8000:8000"
    environment:
      DB_URL:    postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      JWT_SECRET: ${JWT_SECRET}
    depends_on: [redis]

  # ─────────── Redis ───────────
  redis:
    image: redis:7-alpine
    command: ["redis-server",
              "--maxmemory", "128mb",
              "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
