version: "3.9"

services:
  frontend:
    image: ghcr.io/now-eat-krap/one-more-coin/frontend:latest
    ports:
      - "8443:443"  # 내부는 443 유지
    environment:
      DOMAIN: one-more-coin.com
    depends_on: [spring, fastapi]

  spring:
    image: ghcr.io/now-eat-krap/one-more-coin/backend-java:latest
    environment:
      # ...생략
    depends_on: [redis]

  fastapi:
    image: ghcr.io/now-eat-krap/one-more-coin/backend-python:latest
    ports:
      - "8000:8000"
    environment:
      # ...생략
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
