FROM gradle:8.4-jdk17-alpine AS build
WORKDIR /app
COPY . .
RUN gradle clean bootJar --no-daemon

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/build/libs/*.jar backend-java-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "backend-java-0.0.1-SNAPSHOT.jar"]
