name: CI-CD

on:
  push:
    branches: [ main ]

env:
  # !! REPO 이름을 모두 소문자로 고정 !!
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/one-more-coin/app
  SSH_TARGET: ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 1) 소스 체크아웃
    - uses: actions/checkout@v4

    # 2) 멀티 플랫폼 빌드를 위한 buildx 세팅
    - uses: docker/setup-buildx-action@v3

    # 3) GHCR 로그인
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 4) 애플리케이션 이미지(프론트·백엔드·파이썬) 빌드·푸시
    - name: Build & Push images
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest

    # 5) EC2 SSH 접속 → docker compose 업데이트 & 재시작
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.APP_HOST }}
        username: ${{ secrets.APP_USER }}
        key: ${{ secrets.APP_KEY }}
        script: |
          cd ~/app
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f
